version: '3'
services:
  stdf:
    build: ./STDF/
    volumes:
     - ./WeatherData:/usr/local/app/STDF/WeatherData
    restart: always
    expose:
     - "8080"
  nginx:
    image: 'nginx:latest'
    restart: always
    depends_on:
     - stdf
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
